sudo: required
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t suhailibnnisar/learning-docker .

script:
  - docker run suhailibnnisar/learning-docker npm run test:ci

deploy:
  provider: elasticbeanstalk
  app: "learning-docker"
  region: "ap-south-1"
  env: "LearningDocker-env"
  bucket_name: "elasticbeanstalk-ap-south-1-571149291614"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
  access_key_id: $AWS_ACCESS_KEY
  on:
    branch: master
